ntfy:
  url: "https://ntfy.sh"
  topic: "alerts"
  token: ""
  priority: "default"

monitoring:
  containers:
    - "api-service"
    - "worker-service"
  keywords:
    - "exception"
    - "timeout"
    - "unauthorized"
