
containers:
  - "dozzle"
  - "hrconvert2"
keywords:
  - "HTTP"
  - apache
  - "200"
  - "404"
ntfy:
  url: "http://192.168.178.184:82"
  topic: "loggify"
  token: "tk_hjqbstpw4950s0tq466p2nlwnk3k4"

